use mtg;
INSERT INTO sets (name, code) VALUES
('15th Anniversary','15A'),
('Aether Revolt','AER'),
('Alara Reborn','ARB'),
('Alliances','AL'),
('Amonkhet','AKH'),
('Anthologies','ANT'),
('Antiquities','AQ'),
('Apocalypse','AP'),
('Arabian Nights','AN'),
('Archenemy','ARC'),
('Archenemy "Schemes"','ARS'),
('Archenemy: Nicol Bolas','E01'),
('Archenemy: Nicol Bolas "Schemes"','E01S'),
('Arena League','ARE'),
('Asia Pacific Land Program','APAC'),
('Avacyn Restored','AVR'),
('Battle for Zendikar','BFZ'),
('Battle Royale Box Set','BR'),
('Battle the Horde','TBTH'),
('Battlebond','BBD'),
('Beatdown Box Set','BD'),
('Betrayers of Kamigawa','BOK'),
('Born of the Gods','BNG'),
('Celebration Cards','CC'),
('Champions of Kamigawa','CHK'),
('Champs','CHA'),
('Chronicles','CH'),
('Coldsnap','CS'),
('Coldsnap Theme Decks','CST'),
('Commander','CMD'),
('Commander 2013 Edition','C13'),
('Commander 2014 Edition','C14'),
('Commander 2015 Edition','C15'),
('Commander 2016 Edition','C16'),
('Commander 2017 Edition','C17'),
('Commander 2018 Edition','C18'),
('Commander 2019 Edition','C19'),
('Commander Anthology','CMA'),
('Commander Anthology Volume II','CM2'),
('Commander''''s Arsenal','CRS'),
('Conflux','CFX'),
('Conspiracy','CNS'),
('Conspiracy "Conspiracies"','CNSC'),
('Conspiracy: Take the Crown','CN2'),
('Conspiracy: Take the Crown "Conspiracies"','CN2C'),
('Dark Ascension','DKA'),
('Darksteel','DS'),
('Deckmasters','DM'),
('Defeat a God','TDAG'),
('Dissension','DIS'),
('Dominaria','DOM'),
('Dragon''''s Maze','DGM'),
('Dragons of Tarkir','DTK'),
('Duel Decks Anthology, Divine vs. Demonic','ADVD'),
('Duel Decks Anthology, Elves vs. Goblins','AEVG'),
('Duel Decks Anthology, Garruk vs. Liliana','AGVL'),
('Duel Decks Anthology, Jace vs. Chandra','AJVC'),
('Duel Decks: Ajani vs. Nicol Bolas','AVB'),
('Duel Decks: Blessed vs. Cursed','BVC'),
('Duel Decks: Divine vs. Demonic','DVD'),
('Duel Decks: Elspeth vs. Kiora','EVK'),
('Duel Decks: Elspeth vs. Tezzeret','EVT'),
('Duel Decks: Elves vs. Goblins','EVG'),
('Duel Decks: Elves vs. Inventors','EVI'),
('Duel Decks: Garruk vs. Liliana','GVL'),
('Duel Decks: Heroes vs. Monsters','HVM'),
('Duel Decks: Izzet vs. Golgari','IVG'),
('Duel Decks: Jace vs. Chandra','JVC'),
('Duel Decks: Jace vs. Vraska','JVV'),
('Duel Decks: Knights vs. Dragons','KVD'),
('Duel Decks: Merfolk vs. Goblins','MVG'),
('Duel Decks: Mind vs. Might','MVM'),
('Duel Decks: Nissa vs. Ob Nixilis','NVO'),
('Duel Decks: Phyrexia vs. the Coalition','PVC'),
('Duel Decks: Sorin vs. Tibalt','SVT'),
('Duel Decks: Speed vs. Cunning','SVC'),
('Duel Decks: Venser vs. Koth','VVK'),
('Duel Decks: Zendikar vs. Eldrazi','ZVE'),
('Duels of the Planeswalkers','DPW'),
('Eighth Edition','8E'),
('Eldritch Moon','EMN'),
('Eternal Masters','EMA'),
('European Land Program','EUR'),
('Eventide','EVE'),
('Exodus','EX'),
('Explorers of Ixalan','E02'),
('Face the Hydra','TFTH'),
('Fallen Empires','FE'),
('Fate Reforged','FRF'),
('Fifth Dawn','FD'),
('Fifth Edition','5E'),
('Fourth Edition','4E'),
('Friday Night Magic','FNM'),
('From the Vault: Angels','V15'),
('From the Vault: Annihilation','V14'),
('From the Vault: Dragons','V08'),
('From the Vault: Exiled','V09'),
('From the Vault: Legends','V11'),
('From the Vault: Lore','V16'),
('From the Vault: Realms','V12'),
('From the Vault: Relics','V10'),
('From the Vault: Transform','V17'),
('From the Vault: Twenty','V13'),
('Future Sight','FUT'),
('Game Night','GNT'),
('Game Night 2019','GN2'),
('Gatecrash','GTC'),
('Gateway','GTW'),
('Global Series: Jiang Yanggu and Mu Yanling','GS1'),
('Grand Prix','GPX'),
('Guildpact','GP'),
('Guilds of Ravnica','GRN'),
('Guilds of Ravnica Guild Kit','GK1'),
('Guilds of Ravnica Mythic Edition','MED'),
('Guru','GUR'),
('Hachette UK','PHUK'),
('Happy Holidays','HHO'),
('Heroes of the Realm','HTR'),
('Hero''''s Path','THP'),
('Homelands','HL'),
('Hour of Devastation','HOU'),
('Ice Age','IA'),
('Iconic Masters','IMA'),
('Innistrad','ISD'),
('Invasion','IN'),
('Ixalan','XLN'),
('Ixalan Treasure Chest','PXTC'),
('Journey into Nyx','JOU'),
('Judge Gift Program','JGP'),
('Judgment','JU'),
('Kaladesh','KLD'),
('Khans of Tarkir','KTK'),
('Legacy Championship','OLGC'),
('Legendary Cube','PZ1'),
('Legends','LG'),
('Legions','LE'),
('Limited Edition Alpha','A'),
('Limited Edition Beta','B'),
('Lorwyn','LRW'),
('Magic 2010 Core Set','M10'),
('Magic 2011 Core Set','M11'),
('Magic 2012 Core Set','M12'),
('Magic 2013 Core Set','M13'),
('Magic 2014 Core Set','M14'),
('Magic 2015 Core Set','M15'),
('Magic 2019 Core Set','M19'),
('Magic 2020 Core Set','M20'),
('Magic Online Promos','PRM'),
('Magic Origins','ORI'),
('Magic Player Rewards','REW'),
('Magic Premiere Shop','MPSH'),
('Masterpiece Series: Amonkhet Invocations','AKHM'),
('Masterpiece Series: Kaladesh Inventions','KLDM'),
('Masterpiece Series: Zendikar Expeditions','ZENM'),
('Masters 25','A25'),
('Masters Edition','ME1'),
('Masters Edition II','ME2'),
('Masters Edition III','ME3'),
('Masters Edition IV','ME4'),
('Media Inserts','MDI'),
('Mercadian Masques','MM'),
('Mirage','MI'),
('Mirrodin','MR'),
('Mirrodin Besieged','MBS'),
('Modern Event Deck 2014','MD1'),
('Modern Horizons','MH1'),
('Modern Masters','MMA'),
('Modern Masters 2015 Edition','MM2'),
('Modern Masters 2017 Edition','MM3'),
('Morningtide','MOR'),
('Mystery Booster','CMB1'),
('Nemesis','NE'),
('New Phyrexia','NPH'),
('Ninth Edition','9E'),
('Oath of the Gatewatch','OGW'),
('Odyssey','OD'),
('Onslaught','ON'),
('Planar Chaos','PLC'),
('Planechase','PCH'),
('Planechase "Planes"','PCP'),
('Planechase 2012 Edition','PC2'),
('Planechase 2012 Edition "Planes" and "Phenomena"','PP2'),
('Planechase Anthology','PCA'),
('Planechase Anthology "Planes" and "Phenomena"','PCAP'),
('Planeshift','PS'),
('Ponies: The Galloping','PTG'),
('Portal','PT'),
('Portal Second Age','P2'),
('Portal Three Kingdoms','P3'),
('Premium Deck Series: Fire and Lightning','PD2'),
('Premium Deck Series: Graveborn','PD3'),
('Premium Deck Series: Slivers','PD1'),
('Pro Tour Promos','PRO'),
('Prophecy','PY'),
('Ravnica Allegiance','RNA'),
('Ravnica Allegiance Guild Kit','GK2'),
('Ravnica Allegiance Mythic Edition','MED2'),
('Ravnica: City of Guilds','RAV'),
('Release Promos','RLS'),
('Renaissance','REN'),
('Return to Ravnica','RTR'),
('Revised Edition','R'),
('Rise of the Eldrazi','ROE'),
('Rivals of Ixalan','RIX'),
('Salvat 2005','PSAL'),
('Salvat 2011','PS11'),
('Saviors of Kamigawa','SOK'),
('Scars of Mirrodin','SOM'),
('Scourge','SC'),
('Secret Lair Drop','SLD'),
('Seventh Edition','7E'),
('Shadowmoor','SHM'),
('Shadows over Innistrad','SOI'),
('Shards of Alara','ALA'),
('Signature Spellbook: Gideon','SS2'),
('Signature Spellbook: Jace','SS1'),
('Sixth Edition','6E'),
('Starter 1999','ST'),
('Starter 2000','S2'),
('Stronghold','SH'),
('Summer of Magic','SUM'),
('Super Series','SS'),
('Tempest','TE'),
('Tempest Remastered','TPR'),
('Tenth Edition','10E'),
('The Dark','DK'),
('Theros','THS'),
('Theros Beyond Death','THB'),
('Theros Beyond Death Collector Boosters','CTHB'),
('Third Edition Foreign Black Border','3EB'),
('Throne of Eldraine','ELD'),
('Throne of Eldraine Collector Boosters','CELD'),
('Time Spiral','TSP'),
('Time Spiral "Timeshifted"','TSB'),
('Torment','TO'),
('Two-Headed Giant Tournament','2HG'),
('Ugin''''s Fate Promos','UGIN'),
('Ultimate Box Toppers','UMAT'),
('Ultimate Masters','UMA'),
('Unglued','UG'),
('Unhinged','UNH'),
('Unlimited Edition','U'),
('Unsanctioned',''),
('Unstable','UST'),
('Urza''''s Destiny','UD'),
('Urza''''s Legacy','UL'),
('Urza''''s Saga','US'),
('Vintage Championship','OVNC'),
('Vintage Masters','VMA'),
('Visions','VI'),
('War of the Spark','WAR'),
('War of the Spark Mythic Edition','MED3'),
('Weatherlight','WL'),
('Welcome Deck 2016','W16'),
('Welcome Deck 2017','W17'),
('Wizards Play Network','WPN'),
('World Magic Cup Qualifiers','WCQ'),
('Worlds','WRL'),
('Worldwake','WWK'),
('You make the Cube','PZ2'),
('Zendikar','ZEN');